Repository UBCSailbot/network_systems, pull requests merged in 2023-10, with the labels that each got.

#38 User/hhenry01/update build parameters for mongodb
  functions.cmake
  projects/example/CMakeLists.txt
  projects/remote_transceiver/CMakeLists.txt
  projects/remote_transceiver/inc/sailbot_db.h
  projects/remote_transceiver/src/remote_transceiver.cpp
  projects/remote_transceiver/src/sailbot_db.cpp
  projects/remote_transceiver/test/test_remote_transceiver.cpp
Labels: maintenance

#39 Update protobuf package name to Polaris
  lib/protofiles/sensors.proto
  lib/protofiles/waypoints.proto
  projects/remote_transceiver/inc/sailbot_db.h
  projects/remote_transceiver/src/sailbot_db.cpp
  projects/remote_transceiver/test/test_remote_transceiver.cpp
Labels: maintenance

#40 Fix CMake linting
  projects/remote_transceiver/CMakeLists.txt
Labels: bug

#41 Fix mypy errors in launch file
  launch/main_launch.py
Labels: infrastructure

#42 Add mypy CI
  .github/workflows/tests.yml
  launch/main_launch.py
Labels: infrastructure

#45 Minor workflow updates
  CMakeLists.txt
  functions.cmake
  package.xml
  ros_info.txt
Labels: infrastructure

#43 remote transceiver
  lib/cmn_hdrs/shared_constants.h
  lib/protofiles/sensors.proto
  projects/remote_transceiver/inc/sailbot_db.h
  projects/remote_transceiver/src/sailbot_db.cpp
  projects/remote_transceiver/test/test_remote_transceiver.cpp
Labels: enhancement
