Repository UBCSailbot/network_systems, pull requests merged in 2023-11, with the labels that each got.

#53 Fix run_virtual_iridium script
  scripts/run_virtual_iridium.sh
Labels: bug

#52 Local Transceiver Starter Code
  .github/workflows/tests.yml
  functions.cmake
  lib/cmn_hdrs/CMakeLists.txt
  lib/cmn_hdrs/shared_constants.h
  lib/protofiles/sensors.proto
  projects/can_transceiver/src/can_transceiver_ros_intf.cpp
  projects/local_transceiver/CMakeLists.txt
  projects/local_transceiver/inc/at_cmds.h
  projects/local_transceiver/inc/local_transceiver.h
  projects/local_transceiver/src/local_transceiver.cpp
  projects/local_transceiver/src/local_transceiver_ros_intf.cpp
  projects/local_transceiver/test/test_local_transceiver.cpp
  projects/remote_transceiver/src/sailbot_db.cpp
  projects/remote_transceiver/test/test_remote_transceiver.cpp
  scripts/run_virtual_iridium.sh
Labels: enhancement

#57 Make ubcsailbotsoftware a code owner
  .github/CODEOWNERS
Labels: infrastructure

#59 Make ubcsailbotsoftware code owner only for test.yml
  .github/CODEOWNERS
Labels: infrastructure

#58 Add HTTP Interface for Remote Transceiver
  CMakeLists.txt
  lib/protofiles/global_path.proto
  lib/protofiles/sensors.proto
  lib/protofiles/waypoint.proto
  lib/protofiles/waypoints.proto
  projects/remote_transceiver/CMakeLists.txt
  projects/remote_transceiver/inc/remote_transceiver.h
  projects/remote_transceiver/inc/sailbot_db.h
  projects/remote_transceiver/src/main.cpp
  projects/remote_transceiver/src/remote_transceiver.cpp
  projects/remote_transceiver/src/sailbot_db.cpp
  projects/remote_transceiver/test/test_remote_transceiver.cpp
Labels: enhancement

#62 Plantuml Diagrams for CAN, Local, and Remote Transceiver
  .gitignore
  projects/can_transceiver/diagrams/common_sequence.puml
  projects/can_transceiver/diagrams/deployment_sequence.puml
  projects/can_transceiver/diagrams/simulation_sequence.puml
  projects/local_transceiver/diagrams/common.puml
  projects/local_transceiver/diagrams/receive_global_path_sequence.puml
  projects/local_transceiver/diagrams/transmit_sensors_sequence.puml
  projects/remote_transceiver/diagrams/common.puml
  projects/remote_transceiver/diagrams/receive_sensors_sequence.puml
  projects/remote_transceiver/diagrams/transmit_global_path_sequence.puml
Labels: documentation

#63 Fix Can Transceiver Diagram Typos
  projects/can_transceiver/diagrams/common_sequence.puml
  projects/can_transceiver/diagrams/deployment_sequence.puml
  projects/can_transceiver/diagrams/simulation_sequence.puml
Labels: bug, documentation
